repos:
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.2.2
    hooks:
      - id: tofu_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true

      - id: tofu_trivy
        args:
          - --args=--misconfig-scanners=terraform
          - --args=--skip-dirs="**/.terraform"
